from app.repositories.employee_repository import employee_repository
from app.repositories.project_repository import project_repository
from app.repositories.expense_repository import expense_repository
from app.repositories.receipt_repository import receipt_repository
from app.repositories.duplicate_check_repository import duplicate_check_repository
from app.repositories.compliance_check_repository import compliance_check_repository
from app.repositories.approval_repository import approval_repository
from app.repositories.ai_analysis_repository import AIAnalysisRepository