table SpendByCategory
	lineageTag: b1e2c3d4-0002-4a00-8000-000000000001

	column Category
		dataType: string
		lineageTag: b1e2c3d4-0002-4a00-8000-000000000002
		summarizeBy: none
		sourceColumn: Category

	column TotalAmount
		dataType: double
		formatString: "₹"\ #,0.00
		lineageTag: b1e2c3d4-0002-4a00-8000-000000000003
		summarizeBy: sum
		sourceColumn: TotalAmount

	column Count
		dataType: int64
		lineageTag: b1e2c3d4-0002-4a00-8000-000000000004
		summarizeBy: sum
		sourceColumn: Count

	partition SpendByCategory = m
		mode: import
		source =
				let
				    Source = Json.Document(Web.Contents("http://127.0.0.1:8000/api/v1/analytics/spend-by-category")),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"category", "total_amount", "count"}, {"Category", "TotalAmount", "Count"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"Category", type text}, {"TotalAmount", type number}, {"Count", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

