table SpendByProject
	lineageTag: b1e2c3d4-0006-4a00-8000-000000000001

	column ProjectId
		dataType: string
		lineageTag: b1e2c3d4-0006-4a00-8000-000000000002
		summarizeBy: none
		sourceColumn: ProjectId

	column ProjectName
		dataType: string
		lineageTag: b1e2c3d4-0006-4a00-8000-000000000003
		summarizeBy: none
		sourceColumn: ProjectName

	column TotalAmount
		dataType: double
		formatString: "₹"\ #,0.00
		lineageTag: b1e2c3d4-0006-4a00-8000-000000000004
		summarizeBy: sum
		sourceColumn: TotalAmount

	column Count
		dataType: int64
		lineageTag: b1e2c3d4-0006-4a00-8000-000000000005
		summarizeBy: sum
		sourceColumn: Count

	partition SpendByProject = m
		mode: import
		source =
				let
				    Source = Json.Document(Web.Contents("http://127.0.0.1:8000/api/v1/analytics/spend-by-project")),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"project_id", "project_name", "total_amount", "count"}, {"ProjectId", "ProjectName", "TotalAmount", "Count"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"ProjectId", type text}, {"ProjectName", type text}, {"TotalAmount", type number}, {"Count", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

