"""add quality validator fields to ai analysis

Revision ID: 2b130a503ec9
Revises: f06f9e93b696
Create Date: 2026-09-02 18:18:35.332195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b130a503ec9'
down_revision: Union[str, Sequence[str], None] = 'f06f9e93b696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_ai_analysis', sa.Column('quality_issues', sa.String(length=255), nullable=True))
    op.add_column('expense_ai_analysis', sa.Column('requires_reupload', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('expense_ai_analysis', 'requires_reupload', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_ai_analysis', 'requires_reupload')
    op.drop_column('expense_ai_analysis', 'quality_issues')
    # ### end Alembic commands ###
