"""add employee role and hashed_password for JWT auth

Revision ID: 5ddd1db628f8
Revises: 83081f73f0ce
Create Date: 2026-08-26 15:43:03.864648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ddd1db628f8'
down_revision: Union[str, Sequence[str], None] = '83081f73f0ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('role', sa.String(length=20), nullable=False, server_default='EMPLOYEE'))
    op.add_column('employees', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'hashed_password')
    op.drop_column('employees', 'role')
    # ### end Alembic commands ###
