"""add hybrid router, risk scoring, approval routing, reimbursement fields

Revision ID: 83081f73f0ce
Revises: 8fcf6cd4a82c
Create Date: 2026-08-26 14:09:57.161618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83081f73f0ce'
down_revision: Union[str, Sequence[str], None] = '8fcf6cd4a82c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duplicate_checks', sa.Column('matched_expense_id', sa.UUID(), nullable=True))
    op.add_column('duplicate_checks', sa.Column('match_fields', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'duplicate_checks', 'expenses', ['matched_expense_id'], ['id'])
    op.add_column('employees', sa.Column('policy_tier', sa.String(length=20), nullable=False, server_default='STANDARD'))
    op.add_column('expense_ai_analysis', sa.Column('compliance_risk_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('expense_ai_analysis', sa.Column('risk_reason', sa.Text(), nullable=True))
    op.add_column('expense_ai_analysis', sa.Column('required_approval_level', sa.Numeric(precision=2, scale=0), nullable=True))
    op.add_column('expense_approvals', sa.Column('approval_level', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('expenses', sa.Column('is_sensitive', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('expenses', sa.Column('processing_engine', sa.String(length=20), nullable=True))
    op.add_column('expenses', sa.Column('fraud_risk_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('expenses', sa.Column('compliance_risk_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('expenses', sa.Column('ai_confidence_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('expenses', sa.Column('is_duplicate', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('expenses', sa.Column('ai_recommendation', sa.String(length=30), nullable=True))
    op.add_column('expenses', sa.Column('current_approval_level', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('expenses', sa.Column('required_approval_level', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('expenses', sa.Column('reimbursement_state', sa.String(length=20), nullable=False, server_default='PENDING'))
    op.add_column('expenses', sa.Column('reimbursement_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('expenses', sa.Column('reimbursement_processed_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'reimbursement_processed_by')
    op.drop_column('expenses', 'reimbursement_updated_at')
    op.drop_column('expenses', 'reimbursement_state')
    op.drop_column('expenses', 'required_approval_level')
    op.drop_column('expenses', 'current_approval_level')
    op.drop_column('expenses', 'ai_recommendation')
    op.drop_column('expenses', 'is_duplicate')
    op.drop_column('expenses', 'ai_confidence_score')
    op.drop_column('expenses', 'compliance_risk_score')
    op.drop_column('expenses', 'fraud_risk_score')
    op.drop_column('expenses', 'processing_engine')
    op.drop_column('expenses', 'is_sensitive')
    op.drop_column('expense_approvals', 'approval_level')
    op.drop_column('expense_ai_analysis', 'required_approval_level')
    op.drop_column('expense_ai_analysis', 'risk_reason')
    op.drop_column('expense_ai_analysis', 'compliance_risk_score')
    op.drop_column('employees', 'policy_tier')
    op.drop_constraint(None, 'duplicate_checks', type_='foreignkey')
    op.drop_column('duplicate_checks', 'match_fields')
    op.drop_column('duplicate_checks', 'matched_expense_id')
    # ### end Alembic commands ###
