"""...

Revision ID: 8fcf6cd4a82c
Revises: eb243edf8208
Create Date: 2026-07-14 15:18:07.710287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fcf6cd4a82c'
down_revision: Union[str, Sequence[str], None] = 'eb243edf8208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_ai_analysis',
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=True),
    sa.Column('expense_category', sa.String(length=100), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('extracted_json', sa.Text(), nullable=True),
    sa.Column('policy_status', sa.String(length=30), nullable=False),
    sa.Column('policy_reason', sa.Text(), nullable=True),
    sa.Column('requires_manager_approval', sa.Boolean(), nullable=False),
    sa.Column('approval_recommendation', sa.String(length=50), nullable=False),
    sa.Column('ai_provider', sa.String(length=50), nullable=False),
    sa.Column('ocr_provider', sa.String(length=50), nullable=False),
    sa.Column('policy_provider', sa.String(length=50), nullable=False),
    sa.Column('pipeline_version', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fraud_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('duplicate_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_ai_analysis')
    # ### end Alembic commands ###
