"""Add Receipt table

Revision ID: b88fb2de4aa7
Revises: 1c1a210f2c17
Create Date: 2026-07-13 21:28:16.725062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88fb2de4aa7'
down_revision: Union[str, Sequence[str], None] = '1c1a210f2c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('receipt_number', sa.String(length=30), nullable=False))
    op.add_column('receipts', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('receipts', sa.Column('stored_filename', sa.String(length=255), nullable=False))
    op.add_column('receipts', sa.Column('file_size', sa.BigInteger(), nullable=False))
    op.add_column('receipts', sa.Column('upload_status', sa.String(length=30), nullable=False))
    op.alter_column('receipts', 'file_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('receipts_expense_id_key'), 'receipts', type_='unique')
    op.create_index(op.f('ix_receipts_receipt_number'), 'receipts', ['receipt_number'], unique=True)
    op.drop_column('receipts', 'original_file_name')
    op.drop_column('receipts', 'stored_file_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('stored_file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('receipts', sa.Column('original_file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_receipts_receipt_number'), table_name='receipts')
    op.create_unique_constraint(op.f('receipts_expense_id_key'), 'receipts', ['expense_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('receipts', 'file_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('receipts', 'upload_status')
    op.drop_column('receipts', 'file_size')
    op.drop_column('receipts', 'stored_filename')
    op.drop_column('receipts', 'original_filename')
    op.drop_column('receipts', 'receipt_number')
    # ### end Alembic commands ###
