"""add teams, manager chain, drop manager_name

Revision ID: ebfa6460373c
Revises: 5ddd1db628f8
Create Date: 2026-08-31 13:47:03.887496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebfa6460373c'
down_revision: Union[str, Sequence[str], None] = '5ddd1db628f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('team_code', sa.String(length=20), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_team_code'), 'teams', ['team_code'], unique=True)
    op.add_column('employees', sa.Column('manager_id', sa.UUID(), nullable=True))
    op.add_column('employees', sa.Column('team_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'employees', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'employees', ['manager_id'], ['id'])
    op.drop_column('employees', 'manager_name')
    op.add_column('expense_approvals', sa.Column('approver_employee_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'expense_approvals', 'employees', ['approver_employee_id'], ['id'])
    op.add_column('projects', sa.Column('team_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'projects', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'team_id')
    op.drop_constraint(None, 'expense_approvals', type_='foreignkey')
    op.drop_column('expense_approvals', 'approver_employee_id')
    op.add_column('employees', sa.Column('manager_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'team_id')
    op.drop_column('employees', 'manager_id')
    op.drop_index(op.f('ix_teams_team_code'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
